// <auto-generated />
namespace TronCell.Queue.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class version11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version11));
        
        string IMigrationMetadata.Id
        {
            get { return "201411140341561_version1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
